/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/app/AppLayout.vue')['default']
    AppMenu: typeof import('./src/components/app/AppMenu.vue')['default']
    AppMenuItem: typeof import('./src/components/app/AppMenuItem.vue')['default']
    AppSidebar: typeof import('./src/components/app/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/components/app/AppTopbar.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    NiCard: typeof import('./src/components/ui/NiCard.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    TreeTable: typeof import('primevue/treetable')['default']
  }
}
